version: '2'

services:

  dapp-app:
    build:
      context: ./dapp-app
      dockerfile: Dockerfile
    volumes:
      - ./dapp-app:/app
      - /app/node_modules
      - ./dapp-solidity/build:/app/build
    environment:
      - NODE_ENV=development
      - PORT=80
    ports:
      - '8080:80'
    command: npm run dev
  dapp-solidity:
    build:
      context: ./dapp-solidity
      dockerfile: Dockerfile
    environment: 
      - GANACHE_HOST=dapp-ganache
      - INFURA_ENDPOINT=https://rinkeby.infura.io/v3/56e47724040e4929ba2c1d3ff7672387
      - MNEMONIC=toddler tree movie salon object west junior unfair upset lens damage end
    volumes:
      - ./dapp-solidity:/truffle
      - ./dapp-solidity/build:/truffle/build
    # command: ["sleep","36000000"]
    # command: truffle migrate --network rinkeby
    # command: truffle version
    # command: truffle test
    command: npm run test
    depends_on:
      - dapp-ganache
    networks:
      - default
  dapp-ganache:
    image: trufflesuite/ganache-cli:v6.4.2
    command: ganache-cli -m "toddler tree movie salon object west junior unfair upset lens damage end"
    ports:
      - '8545'
    networks:
      - default
  
